Repository prgrms-web-devcourse-final-project/WEB1_2_LinkUP_FE, pull requests merged in 2024-12, with the labels that each got.

#31 Feat: 모바일 반응형 및 카드 스타일 css 컴포넌트 분리
  .env
  package-lock.json
  package.json
  src/assets/icons/menu.svg
  src/components/common/Header.tsx
  src/components/pages/HomePage/CategoryProduct.tsx
  src/components/pages/HomePage/PopularProduct.tsx
  src/components/pages/HomePage/RecommendProduct.tsx
  src/components/pages/HomePage/api/productApi.ts
  src/components/pages/HomePage/model/productSchema.ts
  src/components/pages/HomePage/style/CardStyle.tsx
  src/components/pages/Payment/PaymentForm.tsx
  src/components/pages/Payment/api/paymentApi.ts
  src/components/pages/ProductDetailPage/ProductDetail.tsx
  src/components/pages/ProductDetailPage/api/productDetailApi.ts
  src/components/pages/ProductDetailPage/api/submitApi.ts
  src/components/pages/ProductPage/InputComponent.tsx
  src/components/pages/ProductPage/ProductComponent.tsx
  src/mocks/products.ts
Labels: style, design

#33 Feat: 커뮤니티 공구 모집 및 진행 포스트 결제, 결제 완료 페이지, 관리자 - 게시글 관리 페이지(이전 작업 페이지 수정 사항 포함)
  src/components/common/CategoryWrapper.tsx
  src/components/common/ChatRoom.tsx
  src/components/common/PostList.tsx
  src/components/pages/admin/PostApprovalPage.tsx
  src/components/pages/admin/PostManagementPage.tsx
  src/components/pages/admin/adminCategories.ts
  src/components/pages/admin/api/adminApi.ts
  src/components/pages/community/CategoryBasedPostsPage.tsx
  src/components/pages/community/PaymentAuthorPage.tsx
  src/components/pages/community/PaymentCompletePage.tsx
  src/components/pages/community/PaymentParticipantPage.tsx
  src/components/pages/community/PostCreatePage.tsx
  src/components/pages/community/PostDetailPage.tsx
  src/components/pages/community/PostEditPage.tsx
  src/components/pages/community/api/chatApi.ts
  src/components/pages/community/api/paymentApi.ts
  src/components/pages/community/api/postApi.ts
  src/components/pages/community/modal/ChatRoomModal.tsx
  src/components/pages/community/postCategories.ts
  src/mocks/adminData.ts
  src/mocks/chatData.ts
  src/mocks/communityPosts.ts
  src/routes/router.tsx
  src/utils/webSocket.ts
Labels: feat, fix, refactor, chore

#35 Build: 배포를 위한 dist 생성
  .commitlintrc,json
  dist/assets/index-DCOypNyb.js
  dist/favicon.ico
  dist/images/bell.png
  dist/images/chat.png
  dist/images/chatlist.png
  dist/images/chatlist_on.png
  dist/images/check.png
  dist/images/comment.png
  dist/images/location.png
  dist/images/location_on.png
  dist/images/myposts.png
  dist/images/myposts_on.png
  dist/images/mypostscheck.png
  dist/images/mypostscheck_on.png
  dist/images/notification.png
  dist/images/notification_on.png
  dist/images/orderlist.png
  dist/images/orderlist_on.png
  dist/images/origin.png
  dist/images/qricon.png
  dist/images/refund.png
  dist/images/refund_on.png
  dist/images/search.png
  dist/images/setting.png
  dist/images/setting_on.png
  dist/images/wish.png
  dist/images/wish_on.png
  dist/images/wishlist.png
  dist/images/wishlist_on.png
  dist/index.html
  dist/logo192.png
  dist/logo512.png
  dist/manifest.json
  dist/robots.txt
  package.json
Labels: build

#36 Remove: Delete dist directory
  dist/assets/index-DCOypNyb.js
  dist/favicon.ico
  dist/images/bell.png
  dist/images/chat.png
  dist/images/chatlist.png
  dist/images/chatlist_on.png
  dist/images/check.png
  dist/images/comment.png
  dist/images/location.png
  dist/images/location_on.png
  dist/images/myposts.png
  dist/images/myposts_on.png
  dist/images/mypostscheck.png
  dist/images/mypostscheck_on.png
  dist/images/notification.png
  dist/images/notification_on.png
  dist/images/orderlist.png
  dist/images/orderlist_on.png
  dist/images/origin.png
  dist/images/qricon.png
  dist/images/refund.png
  dist/images/refund_on.png
  dist/images/search.png
  dist/images/setting.png
  dist/images/setting_on.png
  dist/images/wish.png
  dist/images/wish_on.png
  dist/images/wishlist.png
  dist/images/wishlist_on.png
  dist/index.html
  dist/logo192.png
  dist/logo512.png
  dist/manifest.json
  dist/robots.txt
Labels: remove

#39 Fix: import부분 오타 수정
  src/components/pages/ProductDetailPage/ProductDetail.tsx
Labels: fix

#37 Feat: 로그인,회원가입,비밀번호찾기,리셋,현재비밀번호 확인, 동네변경 api 로직 추가
  src/api/loginApi.ts
  src/api/mypageApi.ts
  src/components/pages/login/FindPasswordPage.tsx
  src/components/pages/login/ResetPasswordPage.tsx
  src/components/pages/login/SignInPage.tsx
  src/components/pages/login/SignUpPage.tsx
  src/components/pages/myPage/LocationPage.tsx
  src/components/pages/myPage/Modal/PasswordModal.tsx
Labels: feat

#41 Fix: style-component props 오류 수정 및 각종 경고 수정, cors 코드 추가
  src/components/pages/HomePage/CategoryProduct.tsx
  src/components/pages/HomePage/RecommendProduct.tsx
  src/components/pages/HomePage/model/productSchema.ts
  src/components/pages/HomePage/style/CardStyle.tsx
  src/components/pages/ProductDetailPage/ProductDetail.tsx
  src/components/pages/ProductDetailPage/api/productDetailApi.ts
  src/components/pages/ProductPage/ProductComponent.tsx
  src/components/pages/ProductPage/ProductPage.tsx
  src/main.tsx
  src/mocks/products.ts
  src/routes/router.tsx
  vite.config.mts
Labels: fix

#42 Feat: 회원가입, 로그인 파트 api 연동 완료
  src/api/loginApi.ts
  src/components/pages/login/SetLocationPage.tsx
  src/components/pages/login/SetNicknamePage.tsx
  src/components/pages/login/SetProfilePage.tsx
  src/components/pages/login/SignInPage.tsx
  src/components/pages/login/SignUpPage.tsx
  vite.config.mts
Labels: feat, fix

#45 feat: 로그아웃 기능 추가, 마이페이지 주문내역 api 로직 추가, 결제상태 변경
  public/images/googlelogo.png
  public/images/naverlogo.png
  src/api/mypageApi.ts
  src/components/common/Header.tsx
  src/components/pages/login/SignInPage.tsx
  src/components/pages/myPage/OrderListComponents/OrderHistory.tsx
  src/components/pages/myPage/OrderListPage.tsx
  src/components/pages/myPage/SideMenu.tsx
Labels: feat, fix

#43 Feat: 관리자 - 채팅방 관리 페이지(이전 작업 페이지 수정 사항 포함)
  src/api/axiosInstance.ts
  src/components/common/CategoryWrapper.tsx
  src/components/common/ChatRoom.tsx
  src/components/common/Header.tsx
  src/components/common/PostList.tsx
  src/components/common/ScrollToTopButton.tsx
  src/components/pages/ProductPage/ProductPage.tsx
  src/components/pages/admin/ChatRoomManagementPage.tsx
  src/components/pages/admin/PostApprovalPage.tsx
  src/components/pages/admin/PostManagementPage.tsx
  src/components/pages/admin/api/adminApi.ts
  src/components/pages/community/CategoryBasedPostsPage.tsx
  src/components/pages/community/DepositPage.tsx
  src/components/pages/community/PaymentAuthorPage.tsx
  src/components/pages/community/PaymentCompletePage.tsx
  src/components/pages/community/PaymentParticipantPage.tsx
  src/components/pages/community/PostCreatePage.tsx
  src/components/pages/community/PostDetailPage.tsx
  src/components/pages/community/PostEditPage.tsx
  src/components/pages/community/api/chatApi.ts
  src/components/pages/community/api/paymentApi.ts
  src/components/pages/community/api/postApi.ts
  src/components/pages/community/modal/ChatRoomModal.tsx
  src/components/pages/community/modal/VirtualAccountModal.tsx
  src/components/pages/community/postCategories.ts
  src/mocks/adminData.ts
  src/mocks/chatData.ts
  src/mocks/communityPosts.ts
  src/routes/router.tsx
  src/utils/webSocket.ts
Labels: feat, fix, refactor, chore

#46 Feat: api 연동 및 리팩토링
  .vscode/settings.json
  src/api/axiosInstance.ts
  src/components/common/Header.tsx
  src/components/pages/HomePage/CategoryProduct.tsx
  src/components/pages/HomePage/HomePage.tsx
  src/components/pages/HomePage/model/categories.ts
  src/components/pages/HomePage/model/productSchema.ts
  src/components/pages/Payment/PaymentFailPage.tsx
  src/components/pages/Payment/PaymentForm.tsx
  src/components/pages/Payment/PaymentSuccessPage.tsx
  src/components/pages/Payment/api/paymentApi.ts
  src/components/pages/ProductDetailPage/CommentComponent.tsx
  src/components/pages/ProductDetailPage/ProductDetail.tsx
  src/components/pages/ProductDetailPage/api/CommentApi.ts
  src/components/pages/ProductDetailPage/api/productDetailApi.ts
  src/components/pages/ProductDetailPage/api/submitApi.ts
  src/components/pages/ProductPage/ProductComponent.tsx
  src/components/pages/ProductPage/ProductPage.tsx
  src/components/pages/login/SignInPage.tsx
  src/components/pages/myPage/Modal/LogoutModal.tsx
  src/context/AuthContext.tsx
  src/context/QuantityContext.tsx
  src/main.tsx
  src/mocks/products.ts
  src/routes/ProtectedRoutes.tsx
  src/routes/router.tsx
Labels: feat, fix, refactor, chore

#47 Feat: 마이페이지 각 페이지별 로직 추가, api 적용 완료 / 로그인회원가입 쪽 비밀번호 재설정 로직 추가
  public/images/apple.png
  public/images/towel.jpeg
  public/images/trenchcoat.jpeg
  public/images/vacuum.png
  src/api/mypageApi.ts
  src/components/pages/login/FindPasswordPage.tsx
  src/components/pages/login/ResetPasswordPage.tsx
  src/components/pages/login/SignUpPage.tsx
  src/components/pages/myPage/LocationPage.tsx
  src/components/pages/myPage/MyPostsPage.tsx
  src/components/pages/myPage/OrderListComponents/GroupPurchaseHistory.tsx
  src/components/pages/myPage/OrderListComponents/OrderHistory.tsx
  src/components/pages/myPage/OrderListComponents/RefundHistory.tsx
  src/components/pages/myPage/RefundPage.tsx
  src/components/pages/myPage/SettingPage.tsx
  src/components/pages/myPage/SideMenu.tsx
  src/components/pages/myPage/WishListPage.tsx
  src/components/pages/myPage/mockData.ts
Labels: feat, fix

#48 Chore: 찜기능 주석처리
  src/components/pages/ProductDetailPage/ProductDetail.tsx
Labels: chore

#49 Build: 배포 빌드
  .gitignore
  dist/assets/default-featured-image.png-C2hm5daT.jpg
  dist/assets/index-4YtmX69h.js
  dist/favicon.ico
  dist/images/apple.png
  dist/images/arrow-left.png
  dist/images/bell.png
  dist/images/chat.png
  dist/images/chatlist.png
  dist/images/chatlist_on.png
  dist/images/check.png
  dist/images/comment.png
  dist/images/location.png
  dist/images/location_on.png
  dist/images/login-compl.jpg
  dist/images/login1.jpg
  dist/images/login10.jpg
  dist/images/login11.jpg
  dist/images/login2.jpg
  dist/images/login3.jpg
  dist/images/login4.jpg
  dist/images/login5.jpeg
  dist/images/login6.jpg
  dist/images/login7.jpg
  dist/images/login8.jpeg
  dist/images/login9.jpg
  dist/images/myposts.png
  dist/images/myposts_on.png
  dist/images/mypostscheck.png
  dist/images/mypostscheck_on.png
  dist/images/naverlogo.png
  dist/images/notification.png
  dist/images/notification_on.png
  dist/images/orderlist.png
  dist/images/orderlist_on.png
  dist/images/origin.png
  dist/images/qricon.png
  dist/images/refund.png
  dist/images/refund_on.png
  dist/images/search.png
  dist/images/setting.png
  dist/images/setting_on.png
  dist/images/towel.jpeg
  dist/images/trenchcoat.jpeg
  dist/images/vacuum.png
  dist/images/wish.png
  dist/images/wish_on.png
  dist/images/wishlist.png
  dist/images/wishlist_on.png
  dist/index.html
  dist/logo192.png
  dist/logo512.png
  dist/manifest.json
  dist/robots.txt
  src/components/pages/ProductDetailPage/ProductDetail.tsx
Labels: build

#51 Feat: 실제 API 연동 및 혼합 접근법 활용 상태 관리 추가
  package-lock.json
  package.json
  src/api/axiosInstance.ts
  src/components/common/CategoryWrapper.tsx
  src/components/common/Header.tsx
  src/components/common/PostList.tsx
  src/components/pages/admin/ChatRoomManagementPage.tsx
  src/components/pages/admin/PostApprovalPage.tsx
  src/components/pages/admin/PostManagementPage.tsx
  src/components/pages/admin/api/adminApi.ts
  src/components/pages/community/CategoryBasedPostsPage.tsx
  src/components/pages/community/PaymentAuthorPage.tsx
  src/components/pages/community/PaymentCompletePage.tsx
  src/components/pages/community/PaymentParticipantPage.tsx
  src/components/pages/community/PostCreatePage.tsx
  src/components/pages/community/PostDetailPage.tsx
  src/components/pages/community/PostDetailPage/PostCommentsSection.tsx
  src/components/pages/community/PostDetailPage/PostDetailsSection.tsx
  src/components/pages/community/PostDetailPage/PostImageSection.tsx
  src/components/pages/community/PostEditPage.tsx
  src/components/pages/community/RefundAuthorPage.tsx
  src/components/pages/community/RefundCompletePage.tsx
  src/components/pages/community/RefundParticipantPage.tsx
  src/components/pages/community/api/chatApi.ts
  src/components/pages/community/api/paymentApi.ts
  src/components/pages/community/api/postApi.ts
  src/components/pages/community/postCategories.ts
  src/routes/router.tsx
  src/store/postStore.ts
  src/store/userStore.ts
  src/types/postTypes.ts
  src/utils/GetImageSrc.tsx
  src/utils/formatDate.ts
  src/utils/webSocket.ts
Labels: feat, refactor

#53 Feat: role 추가
  src/api/loginApi.ts
Labels: feat

#52 Fix: 각종 오류 및 요구사항 수정
  src/components/common/Header.tsx
  src/components/pages/Payment/PaymentFailPage.tsx
  src/components/pages/Payment/PaymentSuccessPage.tsx
  src/components/pages/ProductDetailPage/ProductDetail.tsx
  src/components/pages/ProductPage/ProductComponent.tsx
Labels: fix

#54 Feat: 닉네임, 환불 소셜로그인 api 적용, api 실패 시 알람 추가, 주소 풀네임으로 변경
  src/api/mypageApi.ts
  src/components/common/Header.tsx
  src/components/pages/login/FindPasswordPage.tsx
  src/components/pages/login/LoginCompletePage.tsx
  src/components/pages/login/ResetPasswordPage.tsx
  src/components/pages/login/SetLocationPage.tsx
  src/components/pages/login/SetNicknamePage.tsx
  src/components/pages/login/SetProfilePage.tsx
  src/components/pages/login/SignInPage.tsx
  src/components/pages/login/SignUpPage.tsx
  src/components/pages/login/TermsPage.tsx
  src/components/pages/myPage/LocationPage.tsx
  src/components/pages/myPage/OrderListComponents/OrderHistory.tsx
  src/components/pages/myPage/OrderListComponents/RefundHistory.tsx
  src/components/pages/myPage/SettingPage.tsx
Labels: feat, chore

#55 Feat: 프로필 이미지 설정, 유효성검사
  public/images/profile.png
  src/components/pages/login/FindPasswordPage.tsx
  src/components/pages/login/ResetPasswordPage.tsx
  src/components/pages/login/SignInPage.tsx
  src/components/pages/login/SignUpPage.tsx
  src/components/pages/myPage/Modal/PasswordModal.tsx
  src/components/pages/myPage/MyPostsPage.tsx
  src/components/pages/myPage/SettingPage.tsx
  src/components/pages/myPage/SideMenu.tsx
Labels: feat

#56 Feat: SSE 핸들러 및 관리자 전용 참여 현황 열람 기능 추가
  dist/assets/index-BgC4eDEl.js
  dist/assets/index-Dp4wxnjx.js
  dist/index.html
  src/components/common/ChatRoom.tsx
  src/components/common/PostList.tsx
  src/components/pages/admin/ChatRoomManagementPage.tsx
  src/components/pages/admin/PostApprovalPage.tsx
  src/components/pages/admin/PostManagementPage.tsx
  src/components/pages/admin/api/adminApi.ts
  src/components/pages/community/ParticipantList.tsx
  src/components/pages/community/PaymentCompletePage.tsx
  src/components/pages/community/PostCreatePage.tsx
  src/components/pages/community/PostDetailPage.tsx
  src/components/pages/community/PostDetailPage/PostDetailsSection.tsx
  src/components/pages/community/PostEditPage.tsx
  src/components/pages/community/api/chatApi.ts
  src/components/pages/community/api/paymentApi.ts
  src/components/pages/community/api/postApi.ts
  src/components/pages/community/modal/ChatRoomModal.tsx
  src/components/pages/community/modal/VirtualAccountModal.tsx
  src/store/postStore.ts
  src/store/sseStore.ts
  src/store/userStore.ts
  src/types/postTypes.ts
  src/utils/GetImageSrc.tsx
  src/utils/SSEHandler.tsx
  src/utils/webSocket.ts
Labels: feat, chore
