Repository prgrms-web-devcourse-final-project/WEB1_2_LinkUP_FE, pull requests merged in 2024-11, with the labels that each got.

#3 Feat: 홈페이지 기본 컴포넌트 css 구성
  package-lock.json
  package.json
  src/assets/icons/empty.png
  src/assets/icons/graystar.png
  src/assets/icons/icon.png
  src/assets/icons/shopping-cart.png
  src/assets/icons/yellowstar.png
  src/components/common/Header.tsx
  src/components/pages/HomePage.tsx
  src/components/pages/HomePage/CategoryProduct.tsx
  src/components/pages/HomePage/HomePage.tsx
  src/components/pages/HomePage/PopularProduct.tsx
  src/components/pages/HomePage/RecommendProduct.tsx
  src/components/pages/HomePage/api/productApi.ts
  src/components/pages/HomePage/api/userApi.ts
  src/custom.d.ts
  src/routes/router.tsx
  vite.config.mts
Labels: feat, style

#4 Feat: 커뮤니티 공구 모집 및 진행 포스트 목록 조회 페이지
  package-lock.json
  package.json
  src/components/common/CategoryWrapper.tsx
  src/components/common/Pagination.tsx
  src/components/common/PostList.tsx
  src/components/common/ScrollToTopButton.tsx
  src/components/common/SearchBar.tsx
  src/components/common/WriteButton.tsx
  src/components/pages/community/CommunityPage.tsx
  src/mocks/communityPosts.ts
  src/routes/router.tsx
Labels: feat, style, chore

#5 Refactor: Header 컴포넌트를 Layout.tsx에서 관리
  src/components/common/Layout.tsx
  src/components/pages/HomePage/HomePage.tsx
  src/routes/router.tsx
Labels: refactor

#9 Feature: 로그인페이지 비밀번호변경 및 회원가입 페이지 일부 구현
  src/components/pages/login/FindPasswordPage.tsx
  src/components/pages/login/ResetPasswordPage.tsx
  src/components/pages/login/SignInPage.tsx
  src/components/pages/login/SignUpPage.tsx
  src/components/pages/login/TermsPage.tsx
  src/routes/router.tsx
Labels: feat

#11 Feat: 커뮤니티 공구 모집 및 진행 포스트 목록 조회 페이지, 포스트 작성 페이지
  src/api/axiosInstance.ts
  src/components/common/CategoryWrapper.tsx
  src/components/common/PostList.tsx
  src/components/common/WriteButton.tsx
  src/components/pages/community/CategoryBasedPostsPage.tsx
  src/components/pages/community/CommunityPage.tsx
  src/components/pages/community/PostCreatePage.tsx
  src/components/pages/community/api/postApi.ts
  src/mocks/communityPosts.ts
  src/routes/router.tsx
  tsconfig.json
  vite.config.mts
Labels: feat, style, refactor, chore

#12 Feat: 로그인/회원가입 페이지 남은 부분 구성 완료
  public/images/check.png
  public/images/origin.png
  src/components/pages/login/LoginCompletePage.tsx
  src/components/pages/login/SetNicknamePage.tsx
  src/components/pages/login/SetProfilePage.tsx
  src/routes/router.tsx
Labels: feat

#16 Feat : 홈페이지, 물품페이지 수정 및 결제페이지 생성
  src/assets/icons/filled-heart.png
  src/assets/icons/goodbuyus-logo.svg
  src/assets/icons/heart.png
  src/components/common/StarRating.tsx
  src/components/pages/HomePage/CategoryProduct.tsx
  src/components/pages/HomePage/HomePage.tsx
  src/components/pages/HomePage/PopularProduct.tsx
  src/components/pages/HomePage/RecommendProduct.tsx
  src/components/pages/HomePage/api/productApi.ts
  src/components/pages/HomePage/model/productSchema.ts
  src/components/pages/Payment/PaymentForm.tsx
  src/components/pages/Payment/api/paymentApi.ts
  src/components/pages/ProductDetailPage/ProductDetail.tsx
  src/components/pages/ProductDetailPage/api/CommentApi.ts
  src/components/pages/ProductDetailPage/api/WishApi.ts
  src/components/pages/ProductDetailPage/api/productDetailApi.ts
  src/components/pages/ProductPage/ProductComponent.tsx
  src/components/pages/ProductPage/ProductPage.tsx
  src/routes/router.tsx
Labels: feat, style, chore

#15 Feat: 마이페이지(setting / 주문내역, 환불내역, 공구참여내역 탭 / 찜한상품 내역) 구성 완료
  public/images/chatlist.png
  public/images/chatlist_on.png
  public/images/location.png
  public/images/location_on.png
  public/images/myposts.png
  public/images/myposts_on.png
  public/images/notification.png
  public/images/notification_on.png
  public/images/orderlist.png
  public/images/orderlist_on.png
  public/images/refund.png
  public/images/refund_on.png
  public/images/setting.png
  public/images/setting_on.png
  public/images/wishlist.png
  public/images/wishlist_on.png
  src/components/common/Header.tsx
  src/components/pages/myPage/ChatListPage.tsx
  src/components/pages/myPage/GS.ts
  src/components/pages/myPage/LocationPage.tsx
  src/components/pages/myPage/Modal/LogoutModal.tsx
  src/components/pages/myPage/Modal/PasswordModal.tsx
  src/components/pages/myPage/Modal/WithdrawModal.tsx
  src/components/pages/myPage/MyPostsPage.tsx
  src/components/pages/myPage/NotificationPage.tsx
  src/components/pages/myPage/OrderListComponents/GroupPurchaseHistory.tsx
  src/components/pages/myPage/OrderListComponents/OrderHistory.tsx
  src/components/pages/myPage/OrderListComponents/RefundHistory.tsx
  src/components/pages/myPage/OrderListPage.tsx
  src/components/pages/myPage/RefundPage.tsx
  src/components/pages/myPage/SettingPage.tsx
  src/components/pages/myPage/SideMenu.tsx
  src/components/pages/myPage/WishListPage.tsx
  src/components/pages/myPage/mockData.ts
  src/routes/router.tsx
Labels: feat, fix, chore

#19 Feat: 상품 구매 완료 페이지 생성
  src/assets/icons/goodbuyus-logo.svg
  src/components/common/Header.tsx
  src/components/pages/HomePage/CategoryProduct.tsx
  src/components/pages/HomePage/HomePage.tsx
  src/components/pages/HomePage/PopularProduct.tsx
  src/components/pages/HomePage/model/productSchema.ts
  src/components/pages/Payment/PaymentForm.tsx
  src/components/pages/Payment/PaymentSuccessPage.tsx
  src/components/pages/Payment/api/paymentApi.ts
  src/components/pages/ProductDetailPage/ProductDetail.tsx
  src/components/pages/ProductPage/ProductPage.tsx
  src/main.tsx
  src/routes/router.tsx
Labels: feat, fix, design, chore

#21 Feat: 푸터 설정, 페이지 이동 시 최상단으로 나타나게 설정, 반응형
  src/components/common/Footer.tsx
  src/components/common/Layout.tsx
  src/components/common/ScrollToTop.tsx
  src/components/pages/HomePage/CategoryProduct.tsx
  src/components/pages/HomePage/HomePage.tsx
  src/components/pages/HomePage/PopularProduct.tsx
  src/components/pages/HomePage/RecommendProduct.tsx
  src/components/pages/ProductDetailPage/ProductDetail.tsx
  src/components/pages/ProductPage/ProductComponent.tsx
  src/routes/router.tsx
Labels: feat, fix, design

#23 Fix: 주문 내역 각 영역 버튼 수정, 찜한 상품 아이콘 추가
  public/images/chat.png
  public/images/comment.png
  public/images/mypostscheck.png
  public/images/mypostscheck_on.png
  public/images/qricon.png
  public/images/search.png
  public/images/wish.png
  public/images/wish_on.png
  src/components/pages/myPage/OrderListComponents/GroupPurchaseHistory.tsx
  src/components/pages/myPage/OrderListComponents/OrderHistory.tsx
  src/components/pages/myPage/OrderListComponents/RefundHistory.tsx
  src/components/pages/myPage/WishListPage.tsx
Labels: fix, chore

#25 Feat: 동네인증, 환불계좌관리, 알림내역, 나의주문내역 페이지 구성 완료
  public/images/bell.png
  src/components/common/KakaoMap.tsx
  src/components/pages/myPage/LocationPage.tsx
  src/components/pages/myPage/MyPostsPage.tsx
  src/components/pages/myPage/NotificationPage.tsx
  src/components/pages/myPage/RefundPage.tsx
  src/components/pages/myPage/mockData.ts
  src/types/kakao.d.ts
  src/utils/kakaoMapLoader.ts
Labels: feat
